# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinkState(object):
    def setupUi(self, LinkState):
        LinkState.setObjectName("LinkState")
        LinkState.resize(506, 429)
        self.label = QtWidgets.QLabel(LinkState)
        self.label.setGeometry(QtCore.QRect(20, 20, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Modern")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.archivocsv = QtWidgets.QLabel(LinkState)
        self.archivocsv.setGeometry(QtCore.QRect(20, 220, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.archivocsv.setFont(font)
        self.archivocsv.setObjectName("archivocsv")
        self.archivo = QtWidgets.QTextEdit(LinkState)
        self.archivo.setGeometry(QtCore.QRect(20, 260, 291, 31))
        self.archivo.setObjectName("archivo")
        self.pushButton = QtWidgets.QPushButton(LinkState)
        self.pushButton.setGeometry(QtCore.QRect(410, 380, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(LinkState)
        self.radioButton.setGeometry(QtCore.QRect(20, 130, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")

        self.retranslateUi(LinkState)
        QtCore.QMetaObject.connectSlotsByName(LinkState)

    def retranslateUi(self, LinkState):
        _translate = QtCore.QCoreApplication.translate
        LinkState.setWindowTitle(_translate("LinkState", "Form"))
        self.label.setText(_translate("LinkState", "LINK-STATE"))
        self.archivocsv.setText(_translate("LinkState", "Ingrese el nombre del archivo \'.csv\'"))
        self.pushButton.setText(_translate("LinkState", "R U N"))
        self.radioButton.setText(_translate("LinkState", "Generar grafo aleatorio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LinkState = QtWidgets.QWidget()
    ui = Ui_LinkState()
    ui.setupUi(LinkState)
    LinkState.show()
    sys.exit(app.exec_())
