# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinkState(object):
    def setupUi(self, LinkState):
        LinkState.setObjectName("LinkState")
        LinkState.resize(506, 429)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(LinkState.sizePolicy().hasHeightForWidth())
        LinkState.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(LinkState)
        self.label.setGeometry(QtCore.QRect(20, 20, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Modern")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(LinkState)
        self.pushButton.setGeometry(QtCore.QRect(410, 380, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(LinkState)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 110, 171, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(LinkState)
        self.textEdit.setGeometry(QtCore.QRect(220, 210, 191, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(LinkState)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 191, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(LinkState)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 340, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButtom#pushButton_3{\n"
"    background-color:rgba(0,0,0,0)\n"
"    color:rgba(85, 989, 112, 255)\n"
"}\n"
"QPushButtom#pushButton_3:hover{\n"
"    color:rgba(131,96,53,255)\n"
"}\n"
"QPushButtom#pushButton_3:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(91,88,53,255)\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(LinkState)
        QtCore.QMetaObject.connectSlotsByName(LinkState)

    def retranslateUi(self, LinkState):
        _translate = QtCore.QCoreApplication.translate
        LinkState.setWindowTitle(_translate("LinkState", "Form"))
        self.label.setText(_translate("LinkState", "LINK-STATE"))
        self.pushButton.setText(_translate("LinkState", "R U N"))
        self.pushButton_2.setText(_translate("LinkState", "Grafo Aleatorio"))
        self.label_2.setText(_translate("LinkState", "Grafo cargado por archivo \'.csv\'"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LinkState = QtWidgets.QWidget()
    ui = Ui_LinkState()
    ui.setupUi(LinkState)
    LinkState.show()
    sys.exit(app.exec_())
